name: pages
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: {pages: write, id-token: write}
    steps:
      - uses: actions/checkout@v4
        with: {submodules: recursive}
      - run: |
          mkdir -p public
          cp -r sites/fem-product-card public/fem-product-card
          touch public/.nojekyll
      - uses: actions/upload-pages-artifact@v3
        with: {path: public}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions: {pages: write, id-token: write}
    steps:
      - uses: actions/deploy-pages@v4
